print("Drawing:", type(Drawing))
print("Instance:", type(Instance))
print("getgenv:", type(getgenv))
print("IsKeyDown:", pcall(function() return game:GetService("UserInputService"):IsKeyDown(Enum.KeyCode.F1) end))
print("IsMouseButtonPressed:", pcall(function() return game:GetService("UserInputService"):IsMouseButtonPressed(Enum.UserInputType.MouseButton1) end))
print("GetMouseLocation:", pcall(function() return game:GetService("UserInputService"):GetMouseLocation() end))
print("WorldToViewportPoint:", pcall(function() return workspace.CurrentCamera:WorldToViewportPoint(Vector3.new(0,0,0)) end))
print("DrawingSquare:", pcall(function() local s = Drawing.new("Square") s:Remove() return true end))
print("DrawingText:", pcall(function() local t = Drawing.new("Text") t:Remove() return true end))
print("DrawingLine:", pcall(function() local l = Drawing.new("Line") l:Remove() return true end))
