--// TEST WHAT MATCHA SUPPORTS
print("=== MATCHA COMPATIBILITY TEST ===")
print("Drawing:", type(Drawing))
print("Instance:", type(Instance))
print("getgenv:", type(getgenv))
print("getrawmetatable:", type(getrawmetatable))
print("hookfunction:", type(hookfunction))
print("checkcaller:", type(checkcaller))
print("setclipboard:", type(setclipboard))
print("UIS:GetMouseLocation:", pcall(function() return game:GetService("UserInputService"):GetMouseLocation() end))
print("UIS:IsKeyDown(F1):", pcall(function() return game:GetService("UserInputService"):IsKeyDown(Enum.KeyCode.F1) end))
print("UIS:IsMouseButtonPressed:", pcall(function() return game:GetService("UserInputService"):IsMouseButtonPressed(Enum.UserInputType.MouseButton1) end))
print("Camera.WorldToViewportPoint:", pcall(function() return workspace.CurrentCamera:WorldToViewportPoint(Vector3.new(0,0,0)) end))
print("Drawing.new(Square):", pcall(function() local s = Drawing.new("Square") s:Remove() return true end))
print("Drawing.new(Text):", pcall(function() local t = Drawing.new("Text") t:Remove() return true end))
print("Drawing.new(Line):", pcall(function() local l = Drawing.new("Line") l:Remove() return true end))
print("=== END TEST ===")
